### ISSUE TITLE
data/ingest/LOCK already exists; another process is running, or the file is stale

### ISSUE THREAD

**Issue by m247suppport** [oklog/oklog#37]
Hi,

Just testing oklog in the wild, or in an simple alpine container to be specific, and I have come across this upon this:

```
ts=2017-02-06T02:31:56.463440662Z level=info cluster=0.0.0.0:7659
ts=2017-02-06T02:31:56.463619672Z level=info fast=tcp://0.0.0.0:7651
ts=2017-02-06T02:31:56.463676751Z level=info durable=tcp://0.0.0.0:7652
ts=2017-02-06T02:31:56.463725543Z level=info bulk=tcp://0.0.0.0:7653
ts=2017-02-06T02:31:56.463822398Z level=info API=tcp://0.0.0.0:7650
data/ingest/LOCK already exists; another process is running, or the file is stale
```

I *believe* this was a result of having to restart docker, but I can't be 100% sure (not helpful, I know). Oklog is running a pid1, the nobody user runs oklog and oklog is in ingeststore mode (segment-replication-factor 1). Because the container was continually restarting, I was not able to enter into the container in order to attempt to find out more information (I am debating on whether to use something like s6, supervisord or dumb-init to possibly get around this).

If I understand the error correctly, oklog is erroring because both an ingest file and LOCK exist within /data/ingest.

https://github.com/oklog/oklog/blob/ddc43ee9b28e9e59213c0ef33ca658732be93114/pkg/ingest/file_log.go#L35

My question is how does oklog remove the LOCK when the interrupt is issued?

https://github.com/oklog/oklog/blob/64b82eeb53697f6246e9a924e9418f35db2fcb52/cmd/oklog/main.go#L106

https://github.com/oklog/oklog/blob/1bdfb6fab8b72965b018ec7beea6ade78dc4259d/cmd/oklog/ingeststore.go#L442

https://github.com/oklog/oklog/blob/64b82eeb53697f6246e9a924e9418f35db2fcb52/cmd/oklog/main.go#L65

Is this done somehow in pkg/fs? If so, I can't see how this links through to the signal handling in main.

I have not been able to replicate this issue again so far, but I will keep trying.

Any thoughts welcome.

**Comment by peterbourgon** [comment]
Hello! The lock file is created by [ingest.NewFileLog](https://github.com/oklog/oklog/blob/1bdfb6fab8b72965b018ec7beea6ade78dc4259d/pkg/ingest/file_log.go#L30), which is invoked [e.g. here](https://github.com/oklog/oklog/blob/1bdfb6fab8b72965b018ec7beea6ade78dc4259d/cmd/oklog/ingeststore.go#L266); and removed by [ingest.FileLog.Close](https://github.com/oklog/oklog/blob/1bdfb6fab8b72965b018ec7beea6ade78dc4259d/pkg/ingest/file_log.go#L134), which is invoked by a [deferred function call](https://github.com/oklog/oklog/blob/1bdfb6fab8b72965b018ec7beea6ade78dc4259d/cmd/oklog/ingeststore.go#L283). The defer stack is popped when [g.Run()](https://github.com/oklog/oklog/blob/1bdfb6fab8b72965b018ec7beea6ade78dc4259d/cmd/oklog/ingeststore.go#L447) returns, which normally happens when [interrupt returns](https://github.com/oklog/oklog/blob/1bdfb6fab8b72965b018ec7beea6ade78dc4259d/cmd/oklog/ingeststore.go#L442), which is triggered by [SIGINT (2, Ctrl-C) or SIGTERM (15)](https://github.com/oklog/oklog/blob/1bdfb6fab8b72965b018ec7beea6ade78dc4259d/cmd/oklog/main.go#L106). The lock file may remain behind if the process doesn't exit cleanly for whatever reason, e.g. SIGKILL (kill -9). If this happens, and you're sure that no OK Log processes are running, it's totally safe and fine to rm the lock file manually. The next time the ingeststore process starts up, it will recover the state of the disk correctly.

**Comment by m247suppport** [comment]
Thanks for the very useful info! I missed that deferred call. I believe docker will issue a kill signal if it is unable to gracefully stop containers within 30 seconds. My set up is very simple, so I wouldn't have expected oklog to take longer than that amount of time. Given your experience, how long would it usually take oklog to clean up and stop after a SIGINT OR SIGTERM is issued?

**Comment by peterbourgon** [comment]
Depends on your ingest rate, but I typically see shutdown on the order of milliseconds when I'm not heavily loading my system. I'd bet there was some aberration in your Docker daemon that caused a hard kill, especially if you can't easily reproduce.

**Comment by m247suppport** [comment]
Thanks!
